// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for itens documents
 */
interface ItensDocumentData {
  /**
   * title field in *itens*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Nome do item
   * - **API ID Path**: itens.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * description field in *itens*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: itens.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * qnt field in *itens*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: itens.qnt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  qnt: prismic.NumberField;

  /**
   * price field in *itens*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: itens.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  price: prismic.RichTextField;

  /**
   * code field in *itens*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: itens.code
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  code: prismic.RichTextField;

  /**
   * image field in *itens*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: itens.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * image two field in *itens*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: itens.image_two
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_two: prismic.ImageField<never>;

  /**
   * image three field in *itens*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: itens.image_three
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_three: prismic.ImageField<never>;

  /**
   * image four field in *itens*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: itens.image_four
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image_four: prismic.ImageField<never>;

  /**
   * link whats field in *itens*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: itens.link_whats
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_whats: prismic.LinkField;
}

/**
 * itens document from Prismic
 *
 * - **API ID**: `itens`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ItensDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<ItensDocumentData>, "itens", Lang>;

export type AllDocumentTypes = ItensDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type { ItensDocument, ItensDocumentData, AllDocumentTypes };
  }
}
